build:
	docker build -t anry1998/client:1.0.2 . 

run:
	docker run -p 80:80 -d --name client anry1998/client:1.0.2

stop:
	docker stop client

push:
	docker push anry1998/client:1.0.0

pull:
	docker pull anry1998/client:1.0.0