build:
	docker build -t anry1998/server:1.0.0 . 

run:
	docker run --rm -d -p 5000:5000 --name server anry1998/server:1.0.0

stop:
	docker stop server

push:
	docker push anry1998/server:1.0.0

pull:
	docker pull anry1998/server:1.0.0

