FROM nginx
# COPY  client/dist /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
#  CMD ["nginx", "-g", "daemon off;"]


# FROM nginx
# COPY  /client-vite-investigator/dist /usr/share/nginx/html
# COPY ./default.conf /etc/nginx/conf.d/default.conf
# CMD ["nginx", "-g", "daemon off;"]